[platformio]
default_envs = esp32dev

[env]
framework = arduino
board_build.flash_size = 8MB
board_build.partitions = partitions_8mb_ota.csv
monitor_speed = 115200

[env:esp32dev]
platform = espressif32
board = esp32dev
lib_deps = 
    bblanchon/ArduinoJson @ ^7.0
    knolleary/PubSubClient @ ^2.8
    ottowinter/ESPAsyncWebServer-esphome @ ^3.0.0
    tzapu/WiFiManager @ ^2.0

build_flags =
    -DCORE_DEBUG_LEVEL=1
